spring.application.name=user-service
server.port=8000

# User database configuration
spring.datasource.jdbcUrl=jdbc:mysql://localhost:3307/users_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8InnoDBDialect
spring.datasource.jpa.hibernate.ddl-auto=update

# Logging configuration
logging.level.org.hibernate.SQL=info
spring.sql.init.mode=always

# Eureka configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Resilience4j configuration
resilience4j.retry.instances.sample-api.maxRetryAttempts=5
resilience4j.retry.instances.sample-api.waitDuration=1s
resilience4j.retry.instances.sample-api.enableExponentialBackoff=true

resilience4j.ratelimiter.instances.default.limitForPeriod=2
resilience4j.ratelimiter.instances.default.limitRefreshPeriod=10s

resilience4j.bulkhead.instances.default.maxConcurrentCalls=10
resilience4j.bulkhead.instances.sample-api.maxConcurrentCalls=10

# Tracing configuration
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},${X-B3-TraceId:-},${X-B3-SpanId:-}]

# Importing configuration from a Config Server (optional)
spring.config.import=optional:configserver:

# CORS configuration
app.cors.allowedOrigins=*

# Jackson Properties
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Kampala
spring.jackson.time-zone=Africa/Kampala

## Application Properties
app.jwtSecret=e13ed96d548c2f8387471ee5982f277a89f9dd0ad38d2b9e032087e0be54e40d8565c8d25137ae8c766bcdc4dffb551da801f30075e6d84436e048108d67a96c
app.jwtExpirationInMs=10800000
spring.main.allow-circular-references=true
spring.main.lazy-initialization=true

## Auth 2 Configurations
security.oauth2.client.registration.google.clientId=5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
security.oauth2.client.registration.google.clientSecret=tWZKVLxaD_ARWsriiiUFYoIk
security.oauth2.client.registration.google.redirectUri={baseUrl}/oauth2/callback/{registrationId}
security.oauth2.client.registration.google.scope=email,profile

security.oauth2.client.registration.facebook.clientId=121189305185277
security.oauth2.client.registration.facebook.clientSecret=42ffe5aa7379e8326387e0fe16f34132
security.oauth2.client.registration.facebook.redirectUri={baseUrl}/oauth2/callback/{registrationId}
security.oauth2.client.registration.facebook.scope=email,public_profile

security.oauth2.client.registration.github.clientId=d3e47fc2ddd966fa4352
security.oauth2.client.registration.github.clientSecret=3bc0f6b8332f93076354c2a5bada2f5a05aea60d
security.oauth2.client.registration.github.redirectUri={baseUrl}/oauth2/callback/{registrationId}
security.oauth2.client.registration.github.scope=user:email,read:user

security.oauth2.provider.facebook.authorizationUri=https://www.facebook.com/v3.0/dialog/oauth
security.oauth2.provider.facebook.tokenUri=https://graph.facebook.com/v3.0/oauth/access_token
security.oauth2.provider.facebook.userInfoUri=https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

app.oauth2.authorizedRedirectUris=http://localhost:3000/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect



