package com.microservices.templateservice.util.enums;

public enum RoleName {

	ROLE_ADMIN, ROLE_HR, ROLE_ACD, ROLE_ACT, ROLE_DOSA, ROLE_DER, ROLE_USER, ROLE_VC, ROLE_AUDIT, ROLE_DATA, ROLE_SFM,
	ROLE_INV, ROLE_SYSTEM_MONITORING, ROLE_CENTRAL_ACTIVITIES, ROLE_LIBRARY, ROLE_ALPHA_HELP_DESK, ROLE_MIS

}
